from typing import Literal, Optional, TypeAlias

DrawFormat: TypeAlias = Literal["png", "svg"]

class Digraph:
    def __init__(self, format: DrawFormat, graph_attr: Optional[dict[str, str | int | float]]) -> None: ...
    def node(self, name: str, label: Optional[str] = None, shape: Optional[str] = None) -> None: ...
    def edge(self, tail_name: str, head_name: str, label: Optional[str] = None) -> None: ...
